# Generated by Selenium IDE
from idlelib import browser
from telnetlib import EC

import allure
import requests
import pytest
import time
import json
import unittest

from _pytest import unittest
from selenium import webdriver
from selenium.common import ElementNotVisibleException, ElementNotSelectableException, TimeoutException, \
    NoSuchElementException, StaleElementReferenceException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.select import Select
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
options = Options()
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


import unittest
from selenium import webdriver
class test_case1(unittest.TestCase):
    @allure.feature('Open')
    def test1(self):
        s1 ="Ruby"
        s2 ="Ruby"
        # Verifying Numbers
        self.assertTrue(s1 == s2, "It's not a Match.")


class test_case2(unittest.TestCase):
    @allure.feature('Open')
    def test2(self):
        s1 ="Ruby"
        s2 ="Ruby"
        # Verifying Numbers
        self.assertEquals(s1 == s2, "It's not a Match.")
